package com.mama100.lotteryweb.po;

import java.util.Date;

public class BwAd {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_ad.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_ad.sort
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_ad.status
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_ad.system
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String system;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_ad.image
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_ad.app_url
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String appUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_ad.display_brand
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String displayBrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_ad.wx_url
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String wxUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_ad.info
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_ad.operate_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Date operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_ad.end_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_ad.start_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Date startTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_ad.id
     *
     * @return the value of bw_ad.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_ad.id
     *
     * @param id the value for bw_ad.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_ad.sort
     *
     * @return the value of bw_ad.sort
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_ad.sort
     *
     * @param sort the value for bw_ad.sort
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_ad.status
     *
     * @return the value of bw_ad.status
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_ad.status
     *
     * @param status the value for bw_ad.status
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_ad.system
     *
     * @return the value of bw_ad.system
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getSystem() {
        return system;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_ad.system
     *
     * @param system the value for bw_ad.system
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setSystem(String system) {
        this.system = system == null ? null : system.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_ad.image
     *
     * @return the value of bw_ad.image
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_ad.image
     *
     * @param image the value for bw_ad.image
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_ad.app_url
     *
     * @return the value of bw_ad.app_url
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getAppUrl() {
        return appUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_ad.app_url
     *
     * @param appUrl the value for bw_ad.app_url
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setAppUrl(String appUrl) {
        this.appUrl = appUrl == null ? null : appUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_ad.display_brand
     *
     * @return the value of bw_ad.display_brand
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getDisplayBrand() {
        return displayBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_ad.display_brand
     *
     * @param displayBrand the value for bw_ad.display_brand
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setDisplayBrand(String displayBrand) {
        this.displayBrand = displayBrand == null ? null : displayBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_ad.wx_url
     *
     * @return the value of bw_ad.wx_url
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getWxUrl() {
        return wxUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_ad.wx_url
     *
     * @param wxUrl the value for bw_ad.wx_url
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setWxUrl(String wxUrl) {
        this.wxUrl = wxUrl == null ? null : wxUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_ad.info
     *
     * @return the value of bw_ad.info
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_ad.info
     *
     * @param info the value for bw_ad.info
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_ad.operate_time
     *
     * @return the value of bw_ad.operate_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_ad.operate_time
     *
     * @param operateTime the value for bw_ad.operate_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_ad.end_time
     *
     * @return the value of bw_ad.end_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_ad.end_time
     *
     * @param endTime the value for bw_ad.end_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_ad.start_time
     *
     * @return the value of bw_ad.start_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_ad.start_time
     *
     * @param startTime the value for bw_ad.start_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
}