package com.mama100.lotteryweb.po;

public class BwBaseinfoWithBLOBs extends BwBaseinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_baseInfo.receive_terminal
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String receiveTerminal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_baseInfo.trigger_terminal
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String triggerTerminal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_baseInfo.phones
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String phones;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_baseInfo.receive_terminal
     *
     * @return the value of bw_baseInfo.receive_terminal
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getReceiveTerminal() {
        return receiveTerminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_baseInfo.receive_terminal
     *
     * @param receiveTerminal the value for bw_baseInfo.receive_terminal
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setReceiveTerminal(String receiveTerminal) {
        this.receiveTerminal = receiveTerminal == null ? null : receiveTerminal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_baseInfo.trigger_terminal
     *
     * @return the value of bw_baseInfo.trigger_terminal
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getTriggerTerminal() {
        return triggerTerminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_baseInfo.trigger_terminal
     *
     * @param triggerTerminal the value for bw_baseInfo.trigger_terminal
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setTriggerTerminal(String triggerTerminal) {
        this.triggerTerminal = triggerTerminal == null ? null : triggerTerminal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_baseInfo.phones
     *
     * @return the value of bw_baseInfo.phones
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getPhones() {
        return phones;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_baseInfo.phones
     *
     * @param phones the value for bw_baseInfo.phones
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setPhones(String phones) {
        this.phones = phones == null ? null : phones.trim();
    }
}