package com.mama100.lotteryweb.po;

public class BwBonus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_bonus.bonus_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long bonusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_bonus.bonus_type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String bonusType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_bonus.bonus_name
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String bonusName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_bonus.bonus_id
     *
     * @return the value of bw_bonus.bonus_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getBonusId() {
        return bonusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_bonus.bonus_id
     *
     * @param bonusId the value for bw_bonus.bonus_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setBonusId(Long bonusId) {
        this.bonusId = bonusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_bonus.bonus_type
     *
     * @return the value of bw_bonus.bonus_type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getBonusType() {
        return bonusType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_bonus.bonus_type
     *
     * @param bonusType the value for bw_bonus.bonus_type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setBonusType(String bonusType) {
        this.bonusType = bonusType == null ? null : bonusType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_bonus.bonus_name
     *
     * @return the value of bw_bonus.bonus_name
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getBonusName() {
        return bonusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_bonus.bonus_name
     *
     * @param bonusName the value for bw_bonus.bonus_name
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setBonusName(String bonusName) {
        this.bonusName = bonusName == null ? null : bonusName.trim();
    }
}