package com.mama100.lotteryweb.po;

import java.util.ArrayList;
import java.util.List;

public class BwBonusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bw_bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bw_bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bw_bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public BwBonusExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bw_bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBonusIdIsNull() {
            addCriterion("bonus_id is null");
            return (Criteria) this;
        }

        public Criteria andBonusIdIsNotNull() {
            addCriterion("bonus_id is not null");
            return (Criteria) this;
        }

        public Criteria andBonusIdEqualTo(Long value) {
            addCriterion("bonus_id =", value, "bonusId");
            return (Criteria) this;
        }

        public Criteria andBonusIdNotEqualTo(Long value) {
            addCriterion("bonus_id <>", value, "bonusId");
            return (Criteria) this;
        }

        public Criteria andBonusIdGreaterThan(Long value) {
            addCriterion("bonus_id >", value, "bonusId");
            return (Criteria) this;
        }

        public Criteria andBonusIdGreaterThanOrEqualTo(Long value) {
            addCriterion("bonus_id >=", value, "bonusId");
            return (Criteria) this;
        }

        public Criteria andBonusIdLessThan(Long value) {
            addCriterion("bonus_id <", value, "bonusId");
            return (Criteria) this;
        }

        public Criteria andBonusIdLessThanOrEqualTo(Long value) {
            addCriterion("bonus_id <=", value, "bonusId");
            return (Criteria) this;
        }

        public Criteria andBonusIdIn(List<Long> values) {
            addCriterion("bonus_id in", values, "bonusId");
            return (Criteria) this;
        }

        public Criteria andBonusIdNotIn(List<Long> values) {
            addCriterion("bonus_id not in", values, "bonusId");
            return (Criteria) this;
        }

        public Criteria andBonusIdBetween(Long value1, Long value2) {
            addCriterion("bonus_id between", value1, value2, "bonusId");
            return (Criteria) this;
        }

        public Criteria andBonusIdNotBetween(Long value1, Long value2) {
            addCriterion("bonus_id not between", value1, value2, "bonusId");
            return (Criteria) this;
        }

        public Criteria andBonusTypeIsNull() {
            addCriterion("bonus_type is null");
            return (Criteria) this;
        }

        public Criteria andBonusTypeIsNotNull() {
            addCriterion("bonus_type is not null");
            return (Criteria) this;
        }

        public Criteria andBonusTypeEqualTo(String value) {
            addCriterion("bonus_type =", value, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeNotEqualTo(String value) {
            addCriterion("bonus_type <>", value, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeGreaterThan(String value) {
            addCriterion("bonus_type >", value, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeGreaterThanOrEqualTo(String value) {
            addCriterion("bonus_type >=", value, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeLessThan(String value) {
            addCriterion("bonus_type <", value, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeLessThanOrEqualTo(String value) {
            addCriterion("bonus_type <=", value, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeLike(String value) {
            addCriterion("bonus_type like", value, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeNotLike(String value) {
            addCriterion("bonus_type not like", value, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeIn(List<String> values) {
            addCriterion("bonus_type in", values, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeNotIn(List<String> values) {
            addCriterion("bonus_type not in", values, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeBetween(String value1, String value2) {
            addCriterion("bonus_type between", value1, value2, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeNotBetween(String value1, String value2) {
            addCriterion("bonus_type not between", value1, value2, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusNameIsNull() {
            addCriterion("bonus_name is null");
            return (Criteria) this;
        }

        public Criteria andBonusNameIsNotNull() {
            addCriterion("bonus_name is not null");
            return (Criteria) this;
        }

        public Criteria andBonusNameEqualTo(String value) {
            addCriterion("bonus_name =", value, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameNotEqualTo(String value) {
            addCriterion("bonus_name <>", value, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameGreaterThan(String value) {
            addCriterion("bonus_name >", value, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameGreaterThanOrEqualTo(String value) {
            addCriterion("bonus_name >=", value, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameLessThan(String value) {
            addCriterion("bonus_name <", value, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameLessThanOrEqualTo(String value) {
            addCriterion("bonus_name <=", value, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameLike(String value) {
            addCriterion("bonus_name like", value, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameNotLike(String value) {
            addCriterion("bonus_name not like", value, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameIn(List<String> values) {
            addCriterion("bonus_name in", values, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameNotIn(List<String> values) {
            addCriterion("bonus_name not in", values, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameBetween(String value1, String value2) {
            addCriterion("bonus_name between", value1, value2, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameNotBetween(String value1, String value2) {
            addCriterion("bonus_name not between", value1, value2, "bonusName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bw_bonus
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 11 16:35:30 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bw_bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}