package com.mama100.lotteryweb.po;

public class BwGamerule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gameRule.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gameRule.activity_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gameRule.bonus_type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String bonusType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gameRule.bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String bonus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gameRule.times
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Integer times;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gameRule.type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gameRule.id
     *
     * @return the value of bw_gameRule.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gameRule.id
     *
     * @param id the value for bw_gameRule.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gameRule.activity_id
     *
     * @return the value of bw_gameRule.activity_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gameRule.activity_id
     *
     * @param activityId the value for bw_gameRule.activity_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gameRule.bonus_type
     *
     * @return the value of bw_gameRule.bonus_type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getBonusType() {
        return bonusType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gameRule.bonus_type
     *
     * @param bonusType the value for bw_gameRule.bonus_type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setBonusType(String bonusType) {
        this.bonusType = bonusType == null ? null : bonusType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gameRule.bonus
     *
     * @return the value of bw_gameRule.bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getBonus() {
        return bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gameRule.bonus
     *
     * @param bonus the value for bw_gameRule.bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setBonus(String bonus) {
        this.bonus = bonus == null ? null : bonus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gameRule.times
     *
     * @return the value of bw_gameRule.times
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gameRule.times
     *
     * @param times the value for bw_gameRule.times
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gameRule.type
     *
     * @return the value of bw_gameRule.type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gameRule.type
     *
     * @param type the value for bw_gameRule.type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }
}