package com.mama100.lotteryweb.po;

import java.util.Date;

public class BwGametimes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gameTimes.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gameTimes.activity_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gameTimes.user_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gameTimes.user_type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Integer userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gameTimes.times
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Integer times;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gameTimes.status
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gameTimes.info
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gameTimes.operate_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Date operateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gameTimes.id
     *
     * @return the value of bw_gameTimes.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gameTimes.id
     *
     * @param id the value for bw_gameTimes.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gameTimes.activity_id
     *
     * @return the value of bw_gameTimes.activity_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gameTimes.activity_id
     *
     * @param activityId the value for bw_gameTimes.activity_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gameTimes.user_id
     *
     * @return the value of bw_gameTimes.user_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gameTimes.user_id
     *
     * @param userId the value for bw_gameTimes.user_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gameTimes.user_type
     *
     * @return the value of bw_gameTimes.user_type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gameTimes.user_type
     *
     * @param userType the value for bw_gameTimes.user_type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gameTimes.times
     *
     * @return the value of bw_gameTimes.times
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gameTimes.times
     *
     * @param times the value for bw_gameTimes.times
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gameTimes.status
     *
     * @return the value of bw_gameTimes.status
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gameTimes.status
     *
     * @param status the value for bw_gameTimes.status
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gameTimes.info
     *
     * @return the value of bw_gameTimes.info
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gameTimes.info
     *
     * @param info the value for bw_gameTimes.info
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gameTimes.operate_time
     *
     * @return the value of bw_gameTimes.operate_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gameTimes.operate_time
     *
     * @param operateTime the value for bw_gameTimes.operate_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }
}