package com.mama100.lotteryweb.po;

public class BwGoodtips {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_goodTips.tip_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long tipId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_goodTips.activity_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_goodTips.big_tips
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String bigTips;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_goodTips.small_tips
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String smallTips;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_goodTips.updated_by
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String updatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_goodTips.tip_id
     *
     * @return the value of bw_goodTips.tip_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getTipId() {
        return tipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_goodTips.tip_id
     *
     * @param tipId the value for bw_goodTips.tip_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setTipId(Long tipId) {
        this.tipId = tipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_goodTips.activity_id
     *
     * @return the value of bw_goodTips.activity_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_goodTips.activity_id
     *
     * @param activityId the value for bw_goodTips.activity_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_goodTips.big_tips
     *
     * @return the value of bw_goodTips.big_tips
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getBigTips() {
        return bigTips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_goodTips.big_tips
     *
     * @param bigTips the value for bw_goodTips.big_tips
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setBigTips(String bigTips) {
        this.bigTips = bigTips == null ? null : bigTips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_goodTips.small_tips
     *
     * @return the value of bw_goodTips.small_tips
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getSmallTips() {
        return smallTips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_goodTips.small_tips
     *
     * @param smallTips the value for bw_goodTips.small_tips
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setSmallTips(String smallTips) {
        this.smallTips = smallTips == null ? null : smallTips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_goodTips.updated_by
     *
     * @return the value of bw_goodTips.updated_by
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_goodTips.updated_by
     *
     * @param updatedBy the value for bw_goodTips.updated_by
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }
}