package com.mama100.lotteryweb.po;

public class BwGriditem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gridItem.item_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gridItem.activity_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gridItem.sequence
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Integer sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gridItem.grid_name
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String gridName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gridItem.bonus_type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String bonusType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gridItem.bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String bonus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gridItem.bonus_name
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String bonusName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gridItem.bonus_pictureUrl
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String bonusPictureurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gridItem.webp_url
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String webpUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gridItem.big_tips
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String bigTips;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gridItem.small_tips
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String smallTips;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gridItem.free_rate
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Float freeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gridItem.pay_rate
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Float payRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gridItem.quantity
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gridItem.total_quantity
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Integer totalQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gridItem.updated_by
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_gridItem.linked_url
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String linkedUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gridItem.item_id
     *
     * @return the value of bw_gridItem.item_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gridItem.item_id
     *
     * @param itemId the value for bw_gridItem.item_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gridItem.activity_id
     *
     * @return the value of bw_gridItem.activity_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gridItem.activity_id
     *
     * @param activityId the value for bw_gridItem.activity_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gridItem.sequence
     *
     * @return the value of bw_gridItem.sequence
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gridItem.sequence
     *
     * @param sequence the value for bw_gridItem.sequence
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gridItem.grid_name
     *
     * @return the value of bw_gridItem.grid_name
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getGridName() {
        return gridName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gridItem.grid_name
     *
     * @param gridName the value for bw_gridItem.grid_name
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setGridName(String gridName) {
        this.gridName = gridName == null ? null : gridName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gridItem.bonus_type
     *
     * @return the value of bw_gridItem.bonus_type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getBonusType() {
        return bonusType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gridItem.bonus_type
     *
     * @param bonusType the value for bw_gridItem.bonus_type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setBonusType(String bonusType) {
        this.bonusType = bonusType == null ? null : bonusType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gridItem.bonus
     *
     * @return the value of bw_gridItem.bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getBonus() {
        return bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gridItem.bonus
     *
     * @param bonus the value for bw_gridItem.bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setBonus(String bonus) {
        this.bonus = bonus == null ? null : bonus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gridItem.bonus_name
     *
     * @return the value of bw_gridItem.bonus_name
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getBonusName() {
        return bonusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gridItem.bonus_name
     *
     * @param bonusName the value for bw_gridItem.bonus_name
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setBonusName(String bonusName) {
        this.bonusName = bonusName == null ? null : bonusName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gridItem.bonus_pictureUrl
     *
     * @return the value of bw_gridItem.bonus_pictureUrl
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getBonusPictureurl() {
        return bonusPictureurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gridItem.bonus_pictureUrl
     *
     * @param bonusPictureurl the value for bw_gridItem.bonus_pictureUrl
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setBonusPictureurl(String bonusPictureurl) {
        this.bonusPictureurl = bonusPictureurl == null ? null : bonusPictureurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gridItem.webp_url
     *
     * @return the value of bw_gridItem.webp_url
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getWebpUrl() {
        return webpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gridItem.webp_url
     *
     * @param webpUrl the value for bw_gridItem.webp_url
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setWebpUrl(String webpUrl) {
        this.webpUrl = webpUrl == null ? null : webpUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gridItem.big_tips
     *
     * @return the value of bw_gridItem.big_tips
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getBigTips() {
        return bigTips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gridItem.big_tips
     *
     * @param bigTips the value for bw_gridItem.big_tips
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setBigTips(String bigTips) {
        this.bigTips = bigTips == null ? null : bigTips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gridItem.small_tips
     *
     * @return the value of bw_gridItem.small_tips
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getSmallTips() {
        return smallTips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gridItem.small_tips
     *
     * @param smallTips the value for bw_gridItem.small_tips
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setSmallTips(String smallTips) {
        this.smallTips = smallTips == null ? null : smallTips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gridItem.free_rate
     *
     * @return the value of bw_gridItem.free_rate
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Float getFreeRate() {
        return freeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gridItem.free_rate
     *
     * @param freeRate the value for bw_gridItem.free_rate
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setFreeRate(Float freeRate) {
        this.freeRate = freeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gridItem.pay_rate
     *
     * @return the value of bw_gridItem.pay_rate
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Float getPayRate() {
        return payRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gridItem.pay_rate
     *
     * @param payRate the value for bw_gridItem.pay_rate
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setPayRate(Float payRate) {
        this.payRate = payRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gridItem.quantity
     *
     * @return the value of bw_gridItem.quantity
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gridItem.quantity
     *
     * @param quantity the value for bw_gridItem.quantity
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gridItem.total_quantity
     *
     * @return the value of bw_gridItem.total_quantity
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Integer getTotalQuantity() {
        return totalQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gridItem.total_quantity
     *
     * @param totalQuantity the value for bw_gridItem.total_quantity
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setTotalQuantity(Integer totalQuantity) {
        this.totalQuantity = totalQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gridItem.updated_by
     *
     * @return the value of bw_gridItem.updated_by
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gridItem.updated_by
     *
     * @param updatedBy the value for bw_gridItem.updated_by
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_gridItem.linked_url
     *
     * @return the value of bw_gridItem.linked_url
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getLinkedUrl() {
        return linkedUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_gridItem.linked_url
     *
     * @param linkedUrl the value for bw_gridItem.linked_url
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setLinkedUrl(String linkedUrl) {
        this.linkedUrl = linkedUrl == null ? null : linkedUrl.trim();
    }
}