package com.mama100.lotteryweb.po;

import java.util.Date;

public class BwGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_group.group_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_group.status
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_group.code
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_group.description
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_group.created_by
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_group.created_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_group.updated_by
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_group.updated_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_group.group_id
     *
     * @return the value of bw_group.group_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_group.group_id
     *
     * @param groupId the value for bw_group.group_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_group.status
     *
     * @return the value of bw_group.status
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_group.status
     *
     * @param status the value for bw_group.status
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_group.code
     *
     * @return the value of bw_group.code
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_group.code
     *
     * @param code the value for bw_group.code
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_group.description
     *
     * @return the value of bw_group.description
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_group.description
     *
     * @param description the value for bw_group.description
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_group.created_by
     *
     * @return the value of bw_group.created_by
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_group.created_by
     *
     * @param createdBy the value for bw_group.created_by
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_group.created_time
     *
     * @return the value of bw_group.created_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_group.created_time
     *
     * @param createdTime the value for bw_group.created_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_group.updated_by
     *
     * @return the value of bw_group.updated_by
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_group.updated_by
     *
     * @param updatedBy the value for bw_group.updated_by
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_group.updated_time
     *
     * @return the value of bw_group.updated_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_group.updated_time
     *
     * @param updatedTime the value for bw_group.updated_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}