package com.mama100.lotteryweb.po;

public class BwGrouponBaseinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_groupon_baseinfo.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_groupon_baseinfo.group_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_groupon_baseinfo.activity_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long activityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_groupon_baseinfo.id
     *
     * @return the value of bw_groupon_baseinfo.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_groupon_baseinfo.id
     *
     * @param id the value for bw_groupon_baseinfo.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_groupon_baseinfo.group_id
     *
     * @return the value of bw_groupon_baseinfo.group_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_groupon_baseinfo.group_id
     *
     * @param groupId the value for bw_groupon_baseinfo.group_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_groupon_baseinfo.activity_id
     *
     * @return the value of bw_groupon_baseinfo.activity_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_groupon_baseinfo.activity_id
     *
     * @param activityId the value for bw_groupon_baseinfo.activity_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }
}