package com.mama100.lotteryweb.po;

import java.util.Date;

public class BwPoints {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_points.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_points.customer_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_points.status
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_points.point
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Integer point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_points.account_type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String accountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_points.type_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_points.created_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_points.operation_type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String operationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_points.activity_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_points.seq_no
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String seqNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_points.id
     *
     * @return the value of bw_points.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_points.id
     *
     * @param id the value for bw_points.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_points.customer_id
     *
     * @return the value of bw_points.customer_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_points.customer_id
     *
     * @param customerId the value for bw_points.customer_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_points.status
     *
     * @return the value of bw_points.status
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_points.status
     *
     * @param status the value for bw_points.status
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_points.point
     *
     * @return the value of bw_points.point
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_points.point
     *
     * @param point the value for bw_points.point
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_points.account_type
     *
     * @return the value of bw_points.account_type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_points.account_type
     *
     * @param accountType the value for bw_points.account_type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType == null ? null : accountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_points.type_id
     *
     * @return the value of bw_points.type_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_points.type_id
     *
     * @param typeId the value for bw_points.type_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_points.created_time
     *
     * @return the value of bw_points.created_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_points.created_time
     *
     * @param createdTime the value for bw_points.created_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_points.operation_type
     *
     * @return the value of bw_points.operation_type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_points.operation_type
     *
     * @param operationType the value for bw_points.operation_type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType == null ? null : operationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_points.activity_id
     *
     * @return the value of bw_points.activity_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_points.activity_id
     *
     * @param activityId the value for bw_points.activity_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_points.seq_no
     *
     * @return the value of bw_points.seq_no
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_points.seq_no
     *
     * @param seqNo the value for bw_points.seq_no
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setSeqNo(String seqNo) {
        this.seqNo = seqNo == null ? null : seqNo.trim();
    }
}