package com.mama100.lotteryweb.po;

import java.util.Date;

public class BwSignin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_signin.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_signin.customer_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_signin.created_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_signin.times
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Integer times;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_signin.id
     *
     * @return the value of bw_signin.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_signin.id
     *
     * @param id the value for bw_signin.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_signin.customer_id
     *
     * @return the value of bw_signin.customer_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_signin.customer_id
     *
     * @param customerId the value for bw_signin.customer_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_signin.created_time
     *
     * @return the value of bw_signin.created_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_signin.created_time
     *
     * @param createdTime the value for bw_signin.created_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_signin.times
     *
     * @return the value of bw_signin.times
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_signin.times
     *
     * @param times the value for bw_signin.times
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setTimes(Integer times) {
        this.times = times;
    }
}