package com.mama100.lotteryweb.po;

import java.util.Date;

public class BwSystem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_system.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_system.system
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String system;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_system.created_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Date createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_system.id
     *
     * @return the value of bw_system.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_system.id
     *
     * @param id the value for bw_system.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_system.system
     *
     * @return the value of bw_system.system
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getSystem() {
        return system;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_system.system
     *
     * @param system the value for bw_system.system
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setSystem(String system) {
        this.system = system == null ? null : system.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_system.created_time
     *
     * @return the value of bw_system.created_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_system.created_time
     *
     * @param createdTime the value for bw_system.created_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
}