package com.mama100.lotteryweb.po;

import java.util.Date;

public class BwUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_user.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_user.open_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_user.customer_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_user.gender
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Boolean gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_user.mobile
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_user.created_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_user.name
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_user.system
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String system;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_user.id
     *
     * @return the value of bw_user.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_user.id
     *
     * @param id the value for bw_user.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_user.open_id
     *
     * @return the value of bw_user.open_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_user.open_id
     *
     * @param openId the value for bw_user.open_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_user.customer_id
     *
     * @return the value of bw_user.customer_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_user.customer_id
     *
     * @param customerId the value for bw_user.customer_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_user.gender
     *
     * @return the value of bw_user.gender
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_user.gender
     *
     * @param gender the value for bw_user.gender
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_user.mobile
     *
     * @return the value of bw_user.mobile
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_user.mobile
     *
     * @param mobile the value for bw_user.mobile
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_user.created_time
     *
     * @return the value of bw_user.created_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_user.created_time
     *
     * @param createdTime the value for bw_user.created_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_user.name
     *
     * @return the value of bw_user.name
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_user.name
     *
     * @param name the value for bw_user.name
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_user.system
     *
     * @return the value of bw_user.system
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getSystem() {
        return system;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_user.system
     *
     * @param system the value for bw_user.system
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setSystem(String system) {
        this.system = system == null ? null : system.trim();
    }
}