package com.mama100.lotteryweb.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BwUseractionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public BwUseractionExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andActionIdIsNull() {
            addCriterion("action_id is null");
            return (Criteria) this;
        }

        public Criteria andActionIdIsNotNull() {
            addCriterion("action_id is not null");
            return (Criteria) this;
        }

        public Criteria andActionIdEqualTo(Long value) {
            addCriterion("action_id =", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdNotEqualTo(Long value) {
            addCriterion("action_id <>", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdGreaterThan(Long value) {
            addCriterion("action_id >", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdGreaterThanOrEqualTo(Long value) {
            addCriterion("action_id >=", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdLessThan(Long value) {
            addCriterion("action_id <", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdLessThanOrEqualTo(Long value) {
            addCriterion("action_id <=", value, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdIn(List<Long> values) {
            addCriterion("action_id in", values, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdNotIn(List<Long> values) {
            addCriterion("action_id not in", values, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdBetween(Long value1, Long value2) {
            addCriterion("action_id between", value1, value2, "actionId");
            return (Criteria) this;
        }

        public Criteria andActionIdNotBetween(Long value1, Long value2) {
            addCriterion("action_id not between", value1, value2, "actionId");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNull() {
            addCriterion("item_id is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("item_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(Long value) {
            addCriterion("item_id =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(Long value) {
            addCriterion("item_id <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(Long value) {
            addCriterion("item_id >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(Long value) {
            addCriterion("item_id >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(Long value) {
            addCriterion("item_id <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(Long value) {
            addCriterion("item_id <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<Long> values) {
            addCriterion("item_id in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<Long> values) {
            addCriterion("item_id not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(Long value1, Long value2) {
            addCriterion("item_id between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(Long value1, Long value2) {
            addCriterion("item_id not between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andActivityIdIsNull() {
            addCriterion("activity_id is null");
            return (Criteria) this;
        }

        public Criteria andActivityIdIsNotNull() {
            addCriterion("activity_id is not null");
            return (Criteria) this;
        }

        public Criteria andActivityIdEqualTo(Long value) {
            addCriterion("activity_id =", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotEqualTo(Long value) {
            addCriterion("activity_id <>", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdGreaterThan(Long value) {
            addCriterion("activity_id >", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdGreaterThanOrEqualTo(Long value) {
            addCriterion("activity_id >=", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdLessThan(Long value) {
            addCriterion("activity_id <", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdLessThanOrEqualTo(Long value) {
            addCriterion("activity_id <=", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdIn(List<Long> values) {
            addCriterion("activity_id in", values, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotIn(List<Long> values) {
            addCriterion("activity_id not in", values, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdBetween(Long value1, Long value2) {
            addCriterion("activity_id between", value1, value2, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotBetween(Long value1, Long value2) {
            addCriterion("activity_id not between", value1, value2, "activityId");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andActionTimesIsNull() {
            addCriterion("action_times is null");
            return (Criteria) this;
        }

        public Criteria andActionTimesIsNotNull() {
            addCriterion("action_times is not null");
            return (Criteria) this;
        }

        public Criteria andActionTimesEqualTo(Integer value) {
            addCriterion("action_times =", value, "actionTimes");
            return (Criteria) this;
        }

        public Criteria andActionTimesNotEqualTo(Integer value) {
            addCriterion("action_times <>", value, "actionTimes");
            return (Criteria) this;
        }

        public Criteria andActionTimesGreaterThan(Integer value) {
            addCriterion("action_times >", value, "actionTimes");
            return (Criteria) this;
        }

        public Criteria andActionTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("action_times >=", value, "actionTimes");
            return (Criteria) this;
        }

        public Criteria andActionTimesLessThan(Integer value) {
            addCriterion("action_times <", value, "actionTimes");
            return (Criteria) this;
        }

        public Criteria andActionTimesLessThanOrEqualTo(Integer value) {
            addCriterion("action_times <=", value, "actionTimes");
            return (Criteria) this;
        }

        public Criteria andActionTimesIn(List<Integer> values) {
            addCriterion("action_times in", values, "actionTimes");
            return (Criteria) this;
        }

        public Criteria andActionTimesNotIn(List<Integer> values) {
            addCriterion("action_times not in", values, "actionTimes");
            return (Criteria) this;
        }

        public Criteria andActionTimesBetween(Integer value1, Integer value2) {
            addCriterion("action_times between", value1, value2, "actionTimes");
            return (Criteria) this;
        }

        public Criteria andActionTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("action_times not between", value1, value2, "actionTimes");
            return (Criteria) this;
        }

        public Criteria andUserCodeIsNull() {
            addCriterion("user_code is null");
            return (Criteria) this;
        }

        public Criteria andUserCodeIsNotNull() {
            addCriterion("user_code is not null");
            return (Criteria) this;
        }

        public Criteria andUserCodeEqualTo(String value) {
            addCriterion("user_code =", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotEqualTo(String value) {
            addCriterion("user_code <>", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeGreaterThan(String value) {
            addCriterion("user_code >", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeGreaterThanOrEqualTo(String value) {
            addCriterion("user_code >=", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeLessThan(String value) {
            addCriterion("user_code <", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeLessThanOrEqualTo(String value) {
            addCriterion("user_code <=", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeLike(String value) {
            addCriterion("user_code like", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotLike(String value) {
            addCriterion("user_code not like", value, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeIn(List<String> values) {
            addCriterion("user_code in", values, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotIn(List<String> values) {
            addCriterion("user_code not in", values, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeBetween(String value1, String value2) {
            addCriterion("user_code between", value1, value2, "userCode");
            return (Criteria) this;
        }

        public Criteria andUserCodeNotBetween(String value1, String value2) {
            addCriterion("user_code not between", value1, value2, "userCode");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andIsWinningIsNull() {
            addCriterion("is_winning is null");
            return (Criteria) this;
        }

        public Criteria andIsWinningIsNotNull() {
            addCriterion("is_winning is not null");
            return (Criteria) this;
        }

        public Criteria andIsWinningEqualTo(Boolean value) {
            addCriterion("is_winning =", value, "isWinning");
            return (Criteria) this;
        }

        public Criteria andIsWinningNotEqualTo(Boolean value) {
            addCriterion("is_winning <>", value, "isWinning");
            return (Criteria) this;
        }

        public Criteria andIsWinningGreaterThan(Boolean value) {
            addCriterion("is_winning >", value, "isWinning");
            return (Criteria) this;
        }

        public Criteria andIsWinningGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_winning >=", value, "isWinning");
            return (Criteria) this;
        }

        public Criteria andIsWinningLessThan(Boolean value) {
            addCriterion("is_winning <", value, "isWinning");
            return (Criteria) this;
        }

        public Criteria andIsWinningLessThanOrEqualTo(Boolean value) {
            addCriterion("is_winning <=", value, "isWinning");
            return (Criteria) this;
        }

        public Criteria andIsWinningIn(List<Boolean> values) {
            addCriterion("is_winning in", values, "isWinning");
            return (Criteria) this;
        }

        public Criteria andIsWinningNotIn(List<Boolean> values) {
            addCriterion("is_winning not in", values, "isWinning");
            return (Criteria) this;
        }

        public Criteria andIsWinningBetween(Boolean value1, Boolean value2) {
            addCriterion("is_winning between", value1, value2, "isWinning");
            return (Criteria) this;
        }

        public Criteria andIsWinningNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_winning not between", value1, value2, "isWinning");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeIsNull() {
            addCriterion("province_code is null");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeIsNotNull() {
            addCriterion("province_code is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeEqualTo(String value) {
            addCriterion("province_code =", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeNotEqualTo(String value) {
            addCriterion("province_code <>", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeGreaterThan(String value) {
            addCriterion("province_code >", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeGreaterThanOrEqualTo(String value) {
            addCriterion("province_code >=", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeLessThan(String value) {
            addCriterion("province_code <", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeLessThanOrEqualTo(String value) {
            addCriterion("province_code <=", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeLike(String value) {
            addCriterion("province_code like", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeNotLike(String value) {
            addCriterion("province_code not like", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeIn(List<String> values) {
            addCriterion("province_code in", values, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeNotIn(List<String> values) {
            addCriterion("province_code not in", values, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeBetween(String value1, String value2) {
            addCriterion("province_code between", value1, value2, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeNotBetween(String value1, String value2) {
            addCriterion("province_code not between", value1, value2, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("province like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("province not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andCityCodeIsNull() {
            addCriterion("city_code is null");
            return (Criteria) this;
        }

        public Criteria andCityCodeIsNotNull() {
            addCriterion("city_code is not null");
            return (Criteria) this;
        }

        public Criteria andCityCodeEqualTo(String value) {
            addCriterion("city_code =", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeNotEqualTo(String value) {
            addCriterion("city_code <>", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeGreaterThan(String value) {
            addCriterion("city_code >", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeGreaterThanOrEqualTo(String value) {
            addCriterion("city_code >=", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeLessThan(String value) {
            addCriterion("city_code <", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeLessThanOrEqualTo(String value) {
            addCriterion("city_code <=", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeLike(String value) {
            addCriterion("city_code like", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeNotLike(String value) {
            addCriterion("city_code not like", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeIn(List<String> values) {
            addCriterion("city_code in", values, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeNotIn(List<String> values) {
            addCriterion("city_code not in", values, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeBetween(String value1, String value2) {
            addCriterion("city_code between", value1, value2, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeNotBetween(String value1, String value2) {
            addCriterion("city_code not between", value1, value2, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeIsNull() {
            addCriterion("district_code is null");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeIsNotNull() {
            addCriterion("district_code is not null");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeEqualTo(String value) {
            addCriterion("district_code =", value, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeNotEqualTo(String value) {
            addCriterion("district_code <>", value, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeGreaterThan(String value) {
            addCriterion("district_code >", value, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeGreaterThanOrEqualTo(String value) {
            addCriterion("district_code >=", value, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeLessThan(String value) {
            addCriterion("district_code <", value, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeLessThanOrEqualTo(String value) {
            addCriterion("district_code <=", value, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeLike(String value) {
            addCriterion("district_code like", value, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeNotLike(String value) {
            addCriterion("district_code not like", value, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeIn(List<String> values) {
            addCriterion("district_code in", values, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeNotIn(List<String> values) {
            addCriterion("district_code not in", values, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeBetween(String value1, String value2) {
            addCriterion("district_code between", value1, value2, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictCodeNotBetween(String value1, String value2) {
            addCriterion("district_code not between", value1, value2, "districtCode");
            return (Criteria) this;
        }

        public Criteria andDistrictIsNull() {
            addCriterion("district is null");
            return (Criteria) this;
        }

        public Criteria andDistrictIsNotNull() {
            addCriterion("district is not null");
            return (Criteria) this;
        }

        public Criteria andDistrictEqualTo(String value) {
            addCriterion("district =", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictNotEqualTo(String value) {
            addCriterion("district <>", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictGreaterThan(String value) {
            addCriterion("district >", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictGreaterThanOrEqualTo(String value) {
            addCriterion("district >=", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictLessThan(String value) {
            addCriterion("district <", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictLessThanOrEqualTo(String value) {
            addCriterion("district <=", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictLike(String value) {
            addCriterion("district like", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictNotLike(String value) {
            addCriterion("district not like", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictIn(List<String> values) {
            addCriterion("district in", values, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictNotIn(List<String> values) {
            addCriterion("district not in", values, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictBetween(String value1, String value2) {
            addCriterion("district between", value1, value2, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictNotBetween(String value1, String value2) {
            addCriterion("district not between", value1, value2, "district");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andGiftPhoneIsNull() {
            addCriterion("gift_phone is null");
            return (Criteria) this;
        }

        public Criteria andGiftPhoneIsNotNull() {
            addCriterion("gift_phone is not null");
            return (Criteria) this;
        }

        public Criteria andGiftPhoneEqualTo(String value) {
            addCriterion("gift_phone =", value, "giftPhone");
            return (Criteria) this;
        }

        public Criteria andGiftPhoneNotEqualTo(String value) {
            addCriterion("gift_phone <>", value, "giftPhone");
            return (Criteria) this;
        }

        public Criteria andGiftPhoneGreaterThan(String value) {
            addCriterion("gift_phone >", value, "giftPhone");
            return (Criteria) this;
        }

        public Criteria andGiftPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("gift_phone >=", value, "giftPhone");
            return (Criteria) this;
        }

        public Criteria andGiftPhoneLessThan(String value) {
            addCriterion("gift_phone <", value, "giftPhone");
            return (Criteria) this;
        }

        public Criteria andGiftPhoneLessThanOrEqualTo(String value) {
            addCriterion("gift_phone <=", value, "giftPhone");
            return (Criteria) this;
        }

        public Criteria andGiftPhoneLike(String value) {
            addCriterion("gift_phone like", value, "giftPhone");
            return (Criteria) this;
        }

        public Criteria andGiftPhoneNotLike(String value) {
            addCriterion("gift_phone not like", value, "giftPhone");
            return (Criteria) this;
        }

        public Criteria andGiftPhoneIn(List<String> values) {
            addCriterion("gift_phone in", values, "giftPhone");
            return (Criteria) this;
        }

        public Criteria andGiftPhoneNotIn(List<String> values) {
            addCriterion("gift_phone not in", values, "giftPhone");
            return (Criteria) this;
        }

        public Criteria andGiftPhoneBetween(String value1, String value2) {
            addCriterion("gift_phone between", value1, value2, "giftPhone");
            return (Criteria) this;
        }

        public Criteria andGiftPhoneNotBetween(String value1, String value2) {
            addCriterion("gift_phone not between", value1, value2, "giftPhone");
            return (Criteria) this;
        }

        public Criteria andMailCodeIsNull() {
            addCriterion("mail_code is null");
            return (Criteria) this;
        }

        public Criteria andMailCodeIsNotNull() {
            addCriterion("mail_code is not null");
            return (Criteria) this;
        }

        public Criteria andMailCodeEqualTo(String value) {
            addCriterion("mail_code =", value, "mailCode");
            return (Criteria) this;
        }

        public Criteria andMailCodeNotEqualTo(String value) {
            addCriterion("mail_code <>", value, "mailCode");
            return (Criteria) this;
        }

        public Criteria andMailCodeGreaterThan(String value) {
            addCriterion("mail_code >", value, "mailCode");
            return (Criteria) this;
        }

        public Criteria andMailCodeGreaterThanOrEqualTo(String value) {
            addCriterion("mail_code >=", value, "mailCode");
            return (Criteria) this;
        }

        public Criteria andMailCodeLessThan(String value) {
            addCriterion("mail_code <", value, "mailCode");
            return (Criteria) this;
        }

        public Criteria andMailCodeLessThanOrEqualTo(String value) {
            addCriterion("mail_code <=", value, "mailCode");
            return (Criteria) this;
        }

        public Criteria andMailCodeLike(String value) {
            addCriterion("mail_code like", value, "mailCode");
            return (Criteria) this;
        }

        public Criteria andMailCodeNotLike(String value) {
            addCriterion("mail_code not like", value, "mailCode");
            return (Criteria) this;
        }

        public Criteria andMailCodeIn(List<String> values) {
            addCriterion("mail_code in", values, "mailCode");
            return (Criteria) this;
        }

        public Criteria andMailCodeNotIn(List<String> values) {
            addCriterion("mail_code not in", values, "mailCode");
            return (Criteria) this;
        }

        public Criteria andMailCodeBetween(String value1, String value2) {
            addCriterion("mail_code between", value1, value2, "mailCode");
            return (Criteria) this;
        }

        public Criteria andMailCodeNotBetween(String value1, String value2) {
            addCriterion("mail_code not between", value1, value2, "mailCode");
            return (Criteria) this;
        }

        public Criteria andReceivedNameIsNull() {
            addCriterion("received_name is null");
            return (Criteria) this;
        }

        public Criteria andReceivedNameIsNotNull() {
            addCriterion("received_name is not null");
            return (Criteria) this;
        }

        public Criteria andReceivedNameEqualTo(String value) {
            addCriterion("received_name =", value, "receivedName");
            return (Criteria) this;
        }

        public Criteria andReceivedNameNotEqualTo(String value) {
            addCriterion("received_name <>", value, "receivedName");
            return (Criteria) this;
        }

        public Criteria andReceivedNameGreaterThan(String value) {
            addCriterion("received_name >", value, "receivedName");
            return (Criteria) this;
        }

        public Criteria andReceivedNameGreaterThanOrEqualTo(String value) {
            addCriterion("received_name >=", value, "receivedName");
            return (Criteria) this;
        }

        public Criteria andReceivedNameLessThan(String value) {
            addCriterion("received_name <", value, "receivedName");
            return (Criteria) this;
        }

        public Criteria andReceivedNameLessThanOrEqualTo(String value) {
            addCriterion("received_name <=", value, "receivedName");
            return (Criteria) this;
        }

        public Criteria andReceivedNameLike(String value) {
            addCriterion("received_name like", value, "receivedName");
            return (Criteria) this;
        }

        public Criteria andReceivedNameNotLike(String value) {
            addCriterion("received_name not like", value, "receivedName");
            return (Criteria) this;
        }

        public Criteria andReceivedNameIn(List<String> values) {
            addCriterion("received_name in", values, "receivedName");
            return (Criteria) this;
        }

        public Criteria andReceivedNameNotIn(List<String> values) {
            addCriterion("received_name not in", values, "receivedName");
            return (Criteria) this;
        }

        public Criteria andReceivedNameBetween(String value1, String value2) {
            addCriterion("received_name between", value1, value2, "receivedName");
            return (Criteria) this;
        }

        public Criteria andReceivedNameNotBetween(String value1, String value2) {
            addCriterion("received_name not between", value1, value2, "receivedName");
            return (Criteria) this;
        }

        public Criteria andReceivedTimeIsNull() {
            addCriterion("received_time is null");
            return (Criteria) this;
        }

        public Criteria andReceivedTimeIsNotNull() {
            addCriterion("received_time is not null");
            return (Criteria) this;
        }

        public Criteria andReceivedTimeEqualTo(Date value) {
            addCriterion("received_time =", value, "receivedTime");
            return (Criteria) this;
        }

        public Criteria andReceivedTimeNotEqualTo(Date value) {
            addCriterion("received_time <>", value, "receivedTime");
            return (Criteria) this;
        }

        public Criteria andReceivedTimeGreaterThan(Date value) {
            addCriterion("received_time >", value, "receivedTime");
            return (Criteria) this;
        }

        public Criteria andReceivedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("received_time >=", value, "receivedTime");
            return (Criteria) this;
        }

        public Criteria andReceivedTimeLessThan(Date value) {
            addCriterion("received_time <", value, "receivedTime");
            return (Criteria) this;
        }

        public Criteria andReceivedTimeLessThanOrEqualTo(Date value) {
            addCriterion("received_time <=", value, "receivedTime");
            return (Criteria) this;
        }

        public Criteria andReceivedTimeIn(List<Date> values) {
            addCriterion("received_time in", values, "receivedTime");
            return (Criteria) this;
        }

        public Criteria andReceivedTimeNotIn(List<Date> values) {
            addCriterion("received_time not in", values, "receivedTime");
            return (Criteria) this;
        }

        public Criteria andReceivedTimeBetween(Date value1, Date value2) {
            addCriterion("received_time between", value1, value2, "receivedTime");
            return (Criteria) this;
        }

        public Criteria andReceivedTimeNotBetween(Date value1, Date value2) {
            addCriterion("received_time not between", value1, value2, "receivedTime");
            return (Criteria) this;
        }

        public Criteria andHasReceivedIsNull() {
            addCriterion("has_received is null");
            return (Criteria) this;
        }

        public Criteria andHasReceivedIsNotNull() {
            addCriterion("has_received is not null");
            return (Criteria) this;
        }

        public Criteria andHasReceivedEqualTo(Boolean value) {
            addCriterion("has_received =", value, "hasReceived");
            return (Criteria) this;
        }

        public Criteria andHasReceivedNotEqualTo(Boolean value) {
            addCriterion("has_received <>", value, "hasReceived");
            return (Criteria) this;
        }

        public Criteria andHasReceivedGreaterThan(Boolean value) {
            addCriterion("has_received >", value, "hasReceived");
            return (Criteria) this;
        }

        public Criteria andHasReceivedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("has_received >=", value, "hasReceived");
            return (Criteria) this;
        }

        public Criteria andHasReceivedLessThan(Boolean value) {
            addCriterion("has_received <", value, "hasReceived");
            return (Criteria) this;
        }

        public Criteria andHasReceivedLessThanOrEqualTo(Boolean value) {
            addCriterion("has_received <=", value, "hasReceived");
            return (Criteria) this;
        }

        public Criteria andHasReceivedIn(List<Boolean> values) {
            addCriterion("has_received in", values, "hasReceived");
            return (Criteria) this;
        }

        public Criteria andHasReceivedNotIn(List<Boolean> values) {
            addCriterion("has_received not in", values, "hasReceived");
            return (Criteria) this;
        }

        public Criteria andHasReceivedBetween(Boolean value1, Boolean value2) {
            addCriterion("has_received between", value1, value2, "hasReceived");
            return (Criteria) this;
        }

        public Criteria andHasReceivedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("has_received not between", value1, value2, "hasReceived");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNull() {
            addCriterion("updated_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNotNull() {
            addCriterion("updated_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByEqualTo(String value) {
            addCriterion("updated_by =", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotEqualTo(String value) {
            addCriterion("updated_by <>", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThan(String value) {
            addCriterion("updated_by >", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThanOrEqualTo(String value) {
            addCriterion("updated_by >=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThan(String value) {
            addCriterion("updated_by <", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThanOrEqualTo(String value) {
            addCriterion("updated_by <=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLike(String value) {
            addCriterion("updated_by like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotLike(String value) {
            addCriterion("updated_by not like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIn(List<String> values) {
            addCriterion("updated_by in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotIn(List<String> values) {
            addCriterion("updated_by not in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByBetween(String value1, String value2) {
            addCriterion("updated_by between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotBetween(String value1, String value2) {
            addCriterion("updated_by not between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andWinningTimeIsNull() {
            addCriterion("winning_time is null");
            return (Criteria) this;
        }

        public Criteria andWinningTimeIsNotNull() {
            addCriterion("winning_time is not null");
            return (Criteria) this;
        }

        public Criteria andWinningTimeEqualTo(Date value) {
            addCriterion("winning_time =", value, "winningTime");
            return (Criteria) this;
        }

        public Criteria andWinningTimeNotEqualTo(Date value) {
            addCriterion("winning_time <>", value, "winningTime");
            return (Criteria) this;
        }

        public Criteria andWinningTimeGreaterThan(Date value) {
            addCriterion("winning_time >", value, "winningTime");
            return (Criteria) this;
        }

        public Criteria andWinningTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("winning_time >=", value, "winningTime");
            return (Criteria) this;
        }

        public Criteria andWinningTimeLessThan(Date value) {
            addCriterion("winning_time <", value, "winningTime");
            return (Criteria) this;
        }

        public Criteria andWinningTimeLessThanOrEqualTo(Date value) {
            addCriterion("winning_time <=", value, "winningTime");
            return (Criteria) this;
        }

        public Criteria andWinningTimeIn(List<Date> values) {
            addCriterion("winning_time in", values, "winningTime");
            return (Criteria) this;
        }

        public Criteria andWinningTimeNotIn(List<Date> values) {
            addCriterion("winning_time not in", values, "winningTime");
            return (Criteria) this;
        }

        public Criteria andWinningTimeBetween(Date value1, Date value2) {
            addCriterion("winning_time between", value1, value2, "winningTime");
            return (Criteria) this;
        }

        public Criteria andWinningTimeNotBetween(Date value1, Date value2) {
            addCriterion("winning_time not between", value1, value2, "winningTime");
            return (Criteria) this;
        }

        public Criteria andBonusIsNull() {
            addCriterion("bonus is null");
            return (Criteria) this;
        }

        public Criteria andBonusIsNotNull() {
            addCriterion("bonus is not null");
            return (Criteria) this;
        }

        public Criteria andBonusEqualTo(String value) {
            addCriterion("bonus =", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusNotEqualTo(String value) {
            addCriterion("bonus <>", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusGreaterThan(String value) {
            addCriterion("bonus >", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusGreaterThanOrEqualTo(String value) {
            addCriterion("bonus >=", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusLessThan(String value) {
            addCriterion("bonus <", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusLessThanOrEqualTo(String value) {
            addCriterion("bonus <=", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusLike(String value) {
            addCriterion("bonus like", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusNotLike(String value) {
            addCriterion("bonus not like", value, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusIn(List<String> values) {
            addCriterion("bonus in", values, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusNotIn(List<String> values) {
            addCriterion("bonus not in", values, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusBetween(String value1, String value2) {
            addCriterion("bonus between", value1, value2, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusNotBetween(String value1, String value2) {
            addCriterion("bonus not between", value1, value2, "bonus");
            return (Criteria) this;
        }

        public Criteria andBonusTypeIsNull() {
            addCriterion("bonus_type is null");
            return (Criteria) this;
        }

        public Criteria andBonusTypeIsNotNull() {
            addCriterion("bonus_type is not null");
            return (Criteria) this;
        }

        public Criteria andBonusTypeEqualTo(String value) {
            addCriterion("bonus_type =", value, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeNotEqualTo(String value) {
            addCriterion("bonus_type <>", value, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeGreaterThan(String value) {
            addCriterion("bonus_type >", value, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeGreaterThanOrEqualTo(String value) {
            addCriterion("bonus_type >=", value, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeLessThan(String value) {
            addCriterion("bonus_type <", value, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeLessThanOrEqualTo(String value) {
            addCriterion("bonus_type <=", value, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeLike(String value) {
            addCriterion("bonus_type like", value, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeNotLike(String value) {
            addCriterion("bonus_type not like", value, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeIn(List<String> values) {
            addCriterion("bonus_type in", values, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeNotIn(List<String> values) {
            addCriterion("bonus_type not in", values, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeBetween(String value1, String value2) {
            addCriterion("bonus_type between", value1, value2, "bonusType");
            return (Criteria) this;
        }

        public Criteria andBonusTypeNotBetween(String value1, String value2) {
            addCriterion("bonus_type not between", value1, value2, "bonusType");
            return (Criteria) this;
        }

        public Criteria andSystemIsNull() {
            addCriterion("system is null");
            return (Criteria) this;
        }

        public Criteria andSystemIsNotNull() {
            addCriterion("system is not null");
            return (Criteria) this;
        }

        public Criteria andSystemEqualTo(String value) {
            addCriterion("system =", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemNotEqualTo(String value) {
            addCriterion("system <>", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemGreaterThan(String value) {
            addCriterion("system >", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemGreaterThanOrEqualTo(String value) {
            addCriterion("system >=", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemLessThan(String value) {
            addCriterion("system <", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemLessThanOrEqualTo(String value) {
            addCriterion("system <=", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemLike(String value) {
            addCriterion("system like", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemNotLike(String value) {
            addCriterion("system not like", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemIn(List<String> values) {
            addCriterion("system in", values, "system");
            return (Criteria) this;
        }

        public Criteria andSystemNotIn(List<String> values) {
            addCriterion("system not in", values, "system");
            return (Criteria) this;
        }

        public Criteria andSystemBetween(String value1, String value2) {
            addCriterion("system between", value1, value2, "system");
            return (Criteria) this;
        }

        public Criteria andSystemNotBetween(String value1, String value2) {
            addCriterion("system not between", value1, value2, "system");
            return (Criteria) this;
        }

        public Criteria andIsPayIsNull() {
            addCriterion("is_pay is null");
            return (Criteria) this;
        }

        public Criteria andIsPayIsNotNull() {
            addCriterion("is_pay is not null");
            return (Criteria) this;
        }

        public Criteria andIsPayEqualTo(Boolean value) {
            addCriterion("is_pay =", value, "isPay");
            return (Criteria) this;
        }

        public Criteria andIsPayNotEqualTo(Boolean value) {
            addCriterion("is_pay <>", value, "isPay");
            return (Criteria) this;
        }

        public Criteria andIsPayGreaterThan(Boolean value) {
            addCriterion("is_pay >", value, "isPay");
            return (Criteria) this;
        }

        public Criteria andIsPayGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_pay >=", value, "isPay");
            return (Criteria) this;
        }

        public Criteria andIsPayLessThan(Boolean value) {
            addCriterion("is_pay <", value, "isPay");
            return (Criteria) this;
        }

        public Criteria andIsPayLessThanOrEqualTo(Boolean value) {
            addCriterion("is_pay <=", value, "isPay");
            return (Criteria) this;
        }

        public Criteria andIsPayIn(List<Boolean> values) {
            addCriterion("is_pay in", values, "isPay");
            return (Criteria) this;
        }

        public Criteria andIsPayNotIn(List<Boolean> values) {
            addCriterion("is_pay not in", values, "isPay");
            return (Criteria) this;
        }

        public Criteria andIsPayBetween(Boolean value1, Boolean value2) {
            addCriterion("is_pay between", value1, value2, "isPay");
            return (Criteria) this;
        }

        public Criteria andIsPayNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_pay not between", value1, value2, "isPay");
            return (Criteria) this;
        }

        public Criteria andUsedScoreIsNull() {
            addCriterion("used_score is null");
            return (Criteria) this;
        }

        public Criteria andUsedScoreIsNotNull() {
            addCriterion("used_score is not null");
            return (Criteria) this;
        }

        public Criteria andUsedScoreEqualTo(Integer value) {
            addCriterion("used_score =", value, "usedScore");
            return (Criteria) this;
        }

        public Criteria andUsedScoreNotEqualTo(Integer value) {
            addCriterion("used_score <>", value, "usedScore");
            return (Criteria) this;
        }

        public Criteria andUsedScoreGreaterThan(Integer value) {
            addCriterion("used_score >", value, "usedScore");
            return (Criteria) this;
        }

        public Criteria andUsedScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("used_score >=", value, "usedScore");
            return (Criteria) this;
        }

        public Criteria andUsedScoreLessThan(Integer value) {
            addCriterion("used_score <", value, "usedScore");
            return (Criteria) this;
        }

        public Criteria andUsedScoreLessThanOrEqualTo(Integer value) {
            addCriterion("used_score <=", value, "usedScore");
            return (Criteria) this;
        }

        public Criteria andUsedScoreIn(List<Integer> values) {
            addCriterion("used_score in", values, "usedScore");
            return (Criteria) this;
        }

        public Criteria andUsedScoreNotIn(List<Integer> values) {
            addCriterion("used_score not in", values, "usedScore");
            return (Criteria) this;
        }

        public Criteria andUsedScoreBetween(Integer value1, Integer value2) {
            addCriterion("used_score between", value1, value2, "usedScore");
            return (Criteria) this;
        }

        public Criteria andUsedScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("used_score not between", value1, value2, "usedScore");
            return (Criteria) this;
        }

        public Criteria andActivityNameIsNull() {
            addCriterion("activity_name is null");
            return (Criteria) this;
        }

        public Criteria andActivityNameIsNotNull() {
            addCriterion("activity_name is not null");
            return (Criteria) this;
        }

        public Criteria andActivityNameEqualTo(String value) {
            addCriterion("activity_name =", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameNotEqualTo(String value) {
            addCriterion("activity_name <>", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameGreaterThan(String value) {
            addCriterion("activity_name >", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameGreaterThanOrEqualTo(String value) {
            addCriterion("activity_name >=", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameLessThan(String value) {
            addCriterion("activity_name <", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameLessThanOrEqualTo(String value) {
            addCriterion("activity_name <=", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameLike(String value) {
            addCriterion("activity_name like", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameNotLike(String value) {
            addCriterion("activity_name not like", value, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameIn(List<String> values) {
            addCriterion("activity_name in", values, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameNotIn(List<String> values) {
            addCriterion("activity_name not in", values, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameBetween(String value1, String value2) {
            addCriterion("activity_name between", value1, value2, "activityName");
            return (Criteria) this;
        }

        public Criteria andActivityNameNotBetween(String value1, String value2) {
            addCriterion("activity_name not between", value1, value2, "activityName");
            return (Criteria) this;
        }

        public Criteria andBonusNameIsNull() {
            addCriterion("bonus_name is null");
            return (Criteria) this;
        }

        public Criteria andBonusNameIsNotNull() {
            addCriterion("bonus_name is not null");
            return (Criteria) this;
        }

        public Criteria andBonusNameEqualTo(String value) {
            addCriterion("bonus_name =", value, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameNotEqualTo(String value) {
            addCriterion("bonus_name <>", value, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameGreaterThan(String value) {
            addCriterion("bonus_name >", value, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameGreaterThanOrEqualTo(String value) {
            addCriterion("bonus_name >=", value, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameLessThan(String value) {
            addCriterion("bonus_name <", value, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameLessThanOrEqualTo(String value) {
            addCriterion("bonus_name <=", value, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameLike(String value) {
            addCriterion("bonus_name like", value, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameNotLike(String value) {
            addCriterion("bonus_name not like", value, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameIn(List<String> values) {
            addCriterion("bonus_name in", values, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameNotIn(List<String> values) {
            addCriterion("bonus_name not in", values, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameBetween(String value1, String value2) {
            addCriterion("bonus_name between", value1, value2, "bonusName");
            return (Criteria) this;
        }

        public Criteria andBonusNameNotBetween(String value1, String value2) {
            addCriterion("bonus_name not between", value1, value2, "bonusName");
            return (Criteria) this;
        }

        public Criteria andTerminalCodeIsNull() {
            addCriterion("terminal_code is null");
            return (Criteria) this;
        }

        public Criteria andTerminalCodeIsNotNull() {
            addCriterion("terminal_code is not null");
            return (Criteria) this;
        }

        public Criteria andTerminalCodeEqualTo(String value) {
            addCriterion("terminal_code =", value, "terminalCode");
            return (Criteria) this;
        }

        public Criteria andTerminalCodeNotEqualTo(String value) {
            addCriterion("terminal_code <>", value, "terminalCode");
            return (Criteria) this;
        }

        public Criteria andTerminalCodeGreaterThan(String value) {
            addCriterion("terminal_code >", value, "terminalCode");
            return (Criteria) this;
        }

        public Criteria andTerminalCodeGreaterThanOrEqualTo(String value) {
            addCriterion("terminal_code >=", value, "terminalCode");
            return (Criteria) this;
        }

        public Criteria andTerminalCodeLessThan(String value) {
            addCriterion("terminal_code <", value, "terminalCode");
            return (Criteria) this;
        }

        public Criteria andTerminalCodeLessThanOrEqualTo(String value) {
            addCriterion("terminal_code <=", value, "terminalCode");
            return (Criteria) this;
        }

        public Criteria andTerminalCodeLike(String value) {
            addCriterion("terminal_code like", value, "terminalCode");
            return (Criteria) this;
        }

        public Criteria andTerminalCodeNotLike(String value) {
            addCriterion("terminal_code not like", value, "terminalCode");
            return (Criteria) this;
        }

        public Criteria andTerminalCodeIn(List<String> values) {
            addCriterion("terminal_code in", values, "terminalCode");
            return (Criteria) this;
        }

        public Criteria andTerminalCodeNotIn(List<String> values) {
            addCriterion("terminal_code not in", values, "terminalCode");
            return (Criteria) this;
        }

        public Criteria andTerminalCodeBetween(String value1, String value2) {
            addCriterion("terminal_code between", value1, value2, "terminalCode");
            return (Criteria) this;
        }

        public Criteria andTerminalCodeNotBetween(String value1, String value2) {
            addCriterion("terminal_code not between", value1, value2, "terminalCode");
            return (Criteria) this;
        }

        public Criteria andTerminalNameIsNull() {
            addCriterion("terminal_name is null");
            return (Criteria) this;
        }

        public Criteria andTerminalNameIsNotNull() {
            addCriterion("terminal_name is not null");
            return (Criteria) this;
        }

        public Criteria andTerminalNameEqualTo(String value) {
            addCriterion("terminal_name =", value, "terminalName");
            return (Criteria) this;
        }

        public Criteria andTerminalNameNotEqualTo(String value) {
            addCriterion("terminal_name <>", value, "terminalName");
            return (Criteria) this;
        }

        public Criteria andTerminalNameGreaterThan(String value) {
            addCriterion("terminal_name >", value, "terminalName");
            return (Criteria) this;
        }

        public Criteria andTerminalNameGreaterThanOrEqualTo(String value) {
            addCriterion("terminal_name >=", value, "terminalName");
            return (Criteria) this;
        }

        public Criteria andTerminalNameLessThan(String value) {
            addCriterion("terminal_name <", value, "terminalName");
            return (Criteria) this;
        }

        public Criteria andTerminalNameLessThanOrEqualTo(String value) {
            addCriterion("terminal_name <=", value, "terminalName");
            return (Criteria) this;
        }

        public Criteria andTerminalNameLike(String value) {
            addCriterion("terminal_name like", value, "terminalName");
            return (Criteria) this;
        }

        public Criteria andTerminalNameNotLike(String value) {
            addCriterion("terminal_name not like", value, "terminalName");
            return (Criteria) this;
        }

        public Criteria andTerminalNameIn(List<String> values) {
            addCriterion("terminal_name in", values, "terminalName");
            return (Criteria) this;
        }

        public Criteria andTerminalNameNotIn(List<String> values) {
            addCriterion("terminal_name not in", values, "terminalName");
            return (Criteria) this;
        }

        public Criteria andTerminalNameBetween(String value1, String value2) {
            addCriterion("terminal_name between", value1, value2, "terminalName");
            return (Criteria) this;
        }

        public Criteria andTerminalNameNotBetween(String value1, String value2) {
            addCriterion("terminal_name not between", value1, value2, "terminalName");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalNameIsNull() {
            addCriterion("received_terminal_name is null");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalNameIsNotNull() {
            addCriterion("received_terminal_name is not null");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalNameEqualTo(String value) {
            addCriterion("received_terminal_name =", value, "receivedTerminalName");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalNameNotEqualTo(String value) {
            addCriterion("received_terminal_name <>", value, "receivedTerminalName");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalNameGreaterThan(String value) {
            addCriterion("received_terminal_name >", value, "receivedTerminalName");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalNameGreaterThanOrEqualTo(String value) {
            addCriterion("received_terminal_name >=", value, "receivedTerminalName");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalNameLessThan(String value) {
            addCriterion("received_terminal_name <", value, "receivedTerminalName");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalNameLessThanOrEqualTo(String value) {
            addCriterion("received_terminal_name <=", value, "receivedTerminalName");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalNameLike(String value) {
            addCriterion("received_terminal_name like", value, "receivedTerminalName");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalNameNotLike(String value) {
            addCriterion("received_terminal_name not like", value, "receivedTerminalName");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalNameIn(List<String> values) {
            addCriterion("received_terminal_name in", values, "receivedTerminalName");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalNameNotIn(List<String> values) {
            addCriterion("received_terminal_name not in", values, "receivedTerminalName");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalNameBetween(String value1, String value2) {
            addCriterion("received_terminal_name between", value1, value2, "receivedTerminalName");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalNameNotBetween(String value1, String value2) {
            addCriterion("received_terminal_name not between", value1, value2, "receivedTerminalName");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNull() {
            addCriterion("customer_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNotNull() {
            addCriterion("customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdEqualTo(String value) {
            addCriterion("customer_id =", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotEqualTo(String value) {
            addCriterion("customer_id <>", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThan(String value) {
            addCriterion("customer_id >", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThanOrEqualTo(String value) {
            addCriterion("customer_id >=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThan(String value) {
            addCriterion("customer_id <", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThanOrEqualTo(String value) {
            addCriterion("customer_id <=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLike(String value) {
            addCriterion("customer_id like", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotLike(String value) {
            addCriterion("customer_id not like", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIn(List<String> values) {
            addCriterion("customer_id in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotIn(List<String> values) {
            addCriterion("customer_id not in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdBetween(String value1, String value2) {
            addCriterion("customer_id between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotBetween(String value1, String value2) {
            addCriterion("customer_id not between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andOrdercodeIsNull() {
            addCriterion("orderCode is null");
            return (Criteria) this;
        }

        public Criteria andOrdercodeIsNotNull() {
            addCriterion("orderCode is not null");
            return (Criteria) this;
        }

        public Criteria andOrdercodeEqualTo(String value) {
            addCriterion("orderCode =", value, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeNotEqualTo(String value) {
            addCriterion("orderCode <>", value, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeGreaterThan(String value) {
            addCriterion("orderCode >", value, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeGreaterThanOrEqualTo(String value) {
            addCriterion("orderCode >=", value, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeLessThan(String value) {
            addCriterion("orderCode <", value, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeLessThanOrEqualTo(String value) {
            addCriterion("orderCode <=", value, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeLike(String value) {
            addCriterion("orderCode like", value, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeNotLike(String value) {
            addCriterion("orderCode not like", value, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeIn(List<String> values) {
            addCriterion("orderCode in", values, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeNotIn(List<String> values) {
            addCriterion("orderCode not in", values, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeBetween(String value1, String value2) {
            addCriterion("orderCode between", value1, value2, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeNotBetween(String value1, String value2) {
            addCriterion("orderCode not between", value1, value2, "ordercode");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalCodeIsNull() {
            addCriterion("received_terminal_code is null");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalCodeIsNotNull() {
            addCriterion("received_terminal_code is not null");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalCodeEqualTo(String value) {
            addCriterion("received_terminal_code =", value, "receivedTerminalCode");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalCodeNotEqualTo(String value) {
            addCriterion("received_terminal_code <>", value, "receivedTerminalCode");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalCodeGreaterThan(String value) {
            addCriterion("received_terminal_code >", value, "receivedTerminalCode");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalCodeGreaterThanOrEqualTo(String value) {
            addCriterion("received_terminal_code >=", value, "receivedTerminalCode");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalCodeLessThan(String value) {
            addCriterion("received_terminal_code <", value, "receivedTerminalCode");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalCodeLessThanOrEqualTo(String value) {
            addCriterion("received_terminal_code <=", value, "receivedTerminalCode");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalCodeLike(String value) {
            addCriterion("received_terminal_code like", value, "receivedTerminalCode");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalCodeNotLike(String value) {
            addCriterion("received_terminal_code not like", value, "receivedTerminalCode");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalCodeIn(List<String> values) {
            addCriterion("received_terminal_code in", values, "receivedTerminalCode");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalCodeNotIn(List<String> values) {
            addCriterion("received_terminal_code not in", values, "receivedTerminalCode");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalCodeBetween(String value1, String value2) {
            addCriterion("received_terminal_code between", value1, value2, "receivedTerminalCode");
            return (Criteria) this;
        }

        public Criteria andReceivedTerminalCodeNotBetween(String value1, String value2) {
            addCriterion("received_terminal_code not between", value1, value2, "receivedTerminalCode");
            return (Criteria) this;
        }

        public Criteria andReceivedBonusIsNull() {
            addCriterion("received_bonus is null");
            return (Criteria) this;
        }

        public Criteria andReceivedBonusIsNotNull() {
            addCriterion("received_bonus is not null");
            return (Criteria) this;
        }

        public Criteria andReceivedBonusEqualTo(String value) {
            addCriterion("received_bonus =", value, "receivedBonus");
            return (Criteria) this;
        }

        public Criteria andReceivedBonusNotEqualTo(String value) {
            addCriterion("received_bonus <>", value, "receivedBonus");
            return (Criteria) this;
        }

        public Criteria andReceivedBonusGreaterThan(String value) {
            addCriterion("received_bonus >", value, "receivedBonus");
            return (Criteria) this;
        }

        public Criteria andReceivedBonusGreaterThanOrEqualTo(String value) {
            addCriterion("received_bonus >=", value, "receivedBonus");
            return (Criteria) this;
        }

        public Criteria andReceivedBonusLessThan(String value) {
            addCriterion("received_bonus <", value, "receivedBonus");
            return (Criteria) this;
        }

        public Criteria andReceivedBonusLessThanOrEqualTo(String value) {
            addCriterion("received_bonus <=", value, "receivedBonus");
            return (Criteria) this;
        }

        public Criteria andReceivedBonusLike(String value) {
            addCriterion("received_bonus like", value, "receivedBonus");
            return (Criteria) this;
        }

        public Criteria andReceivedBonusNotLike(String value) {
            addCriterion("received_bonus not like", value, "receivedBonus");
            return (Criteria) this;
        }

        public Criteria andReceivedBonusIn(List<String> values) {
            addCriterion("received_bonus in", values, "receivedBonus");
            return (Criteria) this;
        }

        public Criteria andReceivedBonusNotIn(List<String> values) {
            addCriterion("received_bonus not in", values, "receivedBonus");
            return (Criteria) this;
        }

        public Criteria andReceivedBonusBetween(String value1, String value2) {
            addCriterion("received_bonus between", value1, value2, "receivedBonus");
            return (Criteria) this;
        }

        public Criteria andReceivedBonusNotBetween(String value1, String value2) {
            addCriterion("received_bonus not between", value1, value2, "receivedBonus");
            return (Criteria) this;
        }

        public Criteria andWriteOffSystemIsNull() {
            addCriterion("write_off_system is null");
            return (Criteria) this;
        }

        public Criteria andWriteOffSystemIsNotNull() {
            addCriterion("write_off_system is not null");
            return (Criteria) this;
        }

        public Criteria andWriteOffSystemEqualTo(String value) {
            addCriterion("write_off_system =", value, "writeOffSystem");
            return (Criteria) this;
        }

        public Criteria andWriteOffSystemNotEqualTo(String value) {
            addCriterion("write_off_system <>", value, "writeOffSystem");
            return (Criteria) this;
        }

        public Criteria andWriteOffSystemGreaterThan(String value) {
            addCriterion("write_off_system >", value, "writeOffSystem");
            return (Criteria) this;
        }

        public Criteria andWriteOffSystemGreaterThanOrEqualTo(String value) {
            addCriterion("write_off_system >=", value, "writeOffSystem");
            return (Criteria) this;
        }

        public Criteria andWriteOffSystemLessThan(String value) {
            addCriterion("write_off_system <", value, "writeOffSystem");
            return (Criteria) this;
        }

        public Criteria andWriteOffSystemLessThanOrEqualTo(String value) {
            addCriterion("write_off_system <=", value, "writeOffSystem");
            return (Criteria) this;
        }

        public Criteria andWriteOffSystemLike(String value) {
            addCriterion("write_off_system like", value, "writeOffSystem");
            return (Criteria) this;
        }

        public Criteria andWriteOffSystemNotLike(String value) {
            addCriterion("write_off_system not like", value, "writeOffSystem");
            return (Criteria) this;
        }

        public Criteria andWriteOffSystemIn(List<String> values) {
            addCriterion("write_off_system in", values, "writeOffSystem");
            return (Criteria) this;
        }

        public Criteria andWriteOffSystemNotIn(List<String> values) {
            addCriterion("write_off_system not in", values, "writeOffSystem");
            return (Criteria) this;
        }

        public Criteria andWriteOffSystemBetween(String value1, String value2) {
            addCriterion("write_off_system between", value1, value2, "writeOffSystem");
            return (Criteria) this;
        }

        public Criteria andWriteOffSystemNotBetween(String value1, String value2) {
            addCriterion("write_off_system not between", value1, value2, "writeOffSystem");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bw_userAction
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 11 16:35:30 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}