package com.mama100.lotteryweb.po;

import java.util.Date;

public class BwUsererror {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_userError.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_userError.customer_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_userError.bonus_type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String bonusType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_userError.bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String bonus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_userError.detail
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_userError.grid_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Long gridId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_userError.created_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bw_userError.updated_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_userError.id
     *
     * @return the value of bw_userError.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_userError.id
     *
     * @param id the value for bw_userError.id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_userError.customer_id
     *
     * @return the value of bw_userError.customer_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_userError.customer_id
     *
     * @param customerId the value for bw_userError.customer_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_userError.bonus_type
     *
     * @return the value of bw_userError.bonus_type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getBonusType() {
        return bonusType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_userError.bonus_type
     *
     * @param bonusType the value for bw_userError.bonus_type
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setBonusType(String bonusType) {
        this.bonusType = bonusType == null ? null : bonusType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_userError.bonus
     *
     * @return the value of bw_userError.bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getBonus() {
        return bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_userError.bonus
     *
     * @param bonus the value for bw_userError.bonus
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setBonus(String bonus) {
        this.bonus = bonus == null ? null : bonus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_userError.detail
     *
     * @return the value of bw_userError.detail
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_userError.detail
     *
     * @param detail the value for bw_userError.detail
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_userError.grid_id
     *
     * @return the value of bw_userError.grid_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Long getGridId() {
        return gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_userError.grid_id
     *
     * @param gridId the value for bw_userError.grid_id
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setGridId(Long gridId) {
        this.gridId = gridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_userError.created_time
     *
     * @return the value of bw_userError.created_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_userError.created_time
     *
     * @param createdTime the value for bw_userError.created_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bw_userError.updated_time
     *
     * @return the value of bw_userError.updated_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bw_userError.updated_time
     *
     * @param updatedTime the value for bw_userError.updated_time
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}