spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.50.115.114:16052/swisse?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
    username: swisse
    password: swisse
    initialSize: 10
    minIdle: 10
    maxActive: 20
    maxWait: 60000
    useUnfairLock: true
    timeBetweenEvictionRunsMillis: 9000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    removeAbandoned: true
    removeAbandonedTimeout: 1200000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    database: 5  #Redis索引0~15，默认为0
    host: r-wz9z0mr7yzd7wf16hy.redis.rds.aliyuncs.com
    port: 6379
    password: HhBiosTime(*&ASD!@# #密码（默认为空）
    lettuce: # 这里标明使用lettuce配置
      pool:
        max-active: 100   #连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10     #连接池中的最大空闲连接
        min-idle: 5     #连接池中的最小空闲连接
    timeout: 10000    #连接超时时间（毫秒）
# pagehelper分页插件
pagehelper:
  # 数据库的方言
  helperDialect: mysql
  # 启用合理化，如果pageNum < 1会查询第一页，如果pageNum > pages会查询最后一页
  reasonable: true
  
feign:
  url:
    point:
      service: http://p.biostime.it/point-service
