package com.mama100.lotteryweb.mapper;

import com.mama100.lotteryweb.po.BwAd;
import com.mama100.lotteryweb.po.BwAdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BwAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_ad
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    long countByExample(BwAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_ad
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int deleteByExample(BwAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_ad
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_ad
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int insert(BwAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_ad
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int insertSelective(BwAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_ad
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    List<BwAd> selectByExample(BwAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_ad
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    BwAd selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_ad
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByExampleSelective(@Param("record") BwAd record, @Param("example") BwAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_ad
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByExample(@Param("record") BwAd record, @Param("example") BwAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_ad
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByPrimaryKeySelective(BwAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_ad
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByPrimaryKey(BwAd record);
}