package com.mama100.lotteryweb.mapper;

import com.mama100.lotteryweb.po.BwAskreq;
import com.mama100.lotteryweb.po.BwAskreqExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BwAskreqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_askReq
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    long countByExample(BwAskreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_askReq
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int deleteByExample(BwAskreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_askReq
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_askReq
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int insert(BwAskreq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_askReq
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int insertSelective(BwAskreq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_askReq
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    List<BwAskreq> selectByExample(BwAskreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_askReq
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    BwAskreq selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_askReq
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByExampleSelective(@Param("record") BwAskreq record, @Param("example") BwAskreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_askReq
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByExample(@Param("record") BwAskreq record, @Param("example") BwAskreqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_askReq
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByPrimaryKeySelective(BwAskreq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_askReq
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByPrimaryKey(BwAskreq record);
}