package com.mama100.lotteryweb.mapper;

import com.mama100.lotteryweb.po.BwCustomerSignin;
import com.mama100.lotteryweb.po.BwCustomerSigninExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BwCustomerSigninMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_customer_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    long countByExample(BwCustomerSigninExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_customer_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int deleteByExample(BwCustomerSigninExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_customer_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_customer_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int insert(BwCustomerSignin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_customer_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int insertSelective(BwCustomerSignin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_customer_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    List<BwCustomerSignin> selectByExample(BwCustomerSigninExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_customer_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    BwCustomerSignin selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_customer_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByExampleSelective(@Param("record") BwCustomerSignin record, @Param("example") BwCustomerSigninExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_customer_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByExample(@Param("record") BwCustomerSignin record, @Param("example") BwCustomerSigninExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_customer_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByPrimaryKeySelective(BwCustomerSignin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_customer_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByPrimaryKey(BwCustomerSignin record);
}