package com.mama100.lotteryweb.mapper;

import com.mama100.lotteryweb.po.BwGametimes;
import com.mama100.lotteryweb.po.BwGametimesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BwGametimesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gameTimes
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    long countByExample(BwGametimesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gameTimes
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int deleteByExample(BwGametimesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gameTimes
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gameTimes
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int insert(BwGametimes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gameTimes
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int insertSelective(BwGametimes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gameTimes
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    List<BwGametimes> selectByExample(BwGametimesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gameTimes
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    BwGametimes selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gameTimes
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByExampleSelective(@Param("record") BwGametimes record, @Param("example") BwGametimesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gameTimes
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByExample(@Param("record") BwGametimes record, @Param("example") BwGametimesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gameTimes
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByPrimaryKeySelective(BwGametimes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gameTimes
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByPrimaryKey(BwGametimes record);
}