package com.mama100.lotteryweb.mapper;

import com.mama100.lotteryweb.po.BwGriditem;
import com.mama100.lotteryweb.po.BwGriditemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BwGriditemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gridItem
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    long countByExample(BwGriditemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gridItem
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int deleteByExample(BwGriditemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gridItem
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int deleteByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gridItem
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int insert(BwGriditem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gridItem
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int insertSelective(BwGriditem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gridItem
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    List<BwGriditem> selectByExample(BwGriditemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gridItem
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    BwGriditem selectByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gridItem
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByExampleSelective(@Param("record") BwGriditem record, @Param("example") BwGriditemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gridItem
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByExample(@Param("record") BwGriditem record, @Param("example") BwGriditemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gridItem
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByPrimaryKeySelective(BwGriditem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_gridItem
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByPrimaryKey(BwGriditem record);
}