package com.mama100.lotteryweb.mapper;

import com.mama100.lotteryweb.po.BwGrouponBaseinfo;
import com.mama100.lotteryweb.po.BwGrouponBaseinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BwGrouponBaseinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_groupon_baseinfo
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    long countByExample(BwGrouponBaseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_groupon_baseinfo
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int deleteByExample(BwGrouponBaseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_groupon_baseinfo
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_groupon_baseinfo
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int insert(BwGrouponBaseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_groupon_baseinfo
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int insertSelective(BwGrouponBaseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_groupon_baseinfo
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    List<BwGrouponBaseinfo> selectByExample(BwGrouponBaseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_groupon_baseinfo
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    BwGrouponBaseinfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_groupon_baseinfo
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByExampleSelective(@Param("record") BwGrouponBaseinfo record, @Param("example") BwGrouponBaseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_groupon_baseinfo
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByExample(@Param("record") BwGrouponBaseinfo record, @Param("example") BwGrouponBaseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_groupon_baseinfo
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByPrimaryKeySelective(BwGrouponBaseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_groupon_baseinfo
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByPrimaryKey(BwGrouponBaseinfo record);
}