package com.mama100.lotteryweb.mapper;

import com.mama100.lotteryweb.po.BwGroup;
import com.mama100.lotteryweb.po.BwGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BwGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_group
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    long countByExample(BwGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_group
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int deleteByExample(BwGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_group
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int deleteByPrimaryKey(Long groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_group
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int insert(BwGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_group
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int insertSelective(BwGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_group
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    List<BwGroup> selectByExample(BwGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_group
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    BwGroup selectByPrimaryKey(Long groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_group
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByExampleSelective(@Param("record") BwGroup record, @Param("example") BwGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_group
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByExample(@Param("record") BwGroup record, @Param("example") BwGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_group
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByPrimaryKeySelective(BwGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_group
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByPrimaryKey(BwGroup record);
}