package com.mama100.lotteryweb.mapper;

import com.mama100.lotteryweb.po.BwHealthmonitoring;
import com.mama100.lotteryweb.po.BwHealthmonitoringExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BwHealthmonitoringMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_healthMonitoring
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    long countByExample(BwHealthmonitoringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_healthMonitoring
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int deleteByExample(BwHealthmonitoringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_healthMonitoring
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_healthMonitoring
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int insert(BwHealthmonitoring record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_healthMonitoring
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int insertSelective(BwHealthmonitoring record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_healthMonitoring
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    List<BwHealthmonitoring> selectByExample(BwHealthmonitoringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_healthMonitoring
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    BwHealthmonitoring selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_healthMonitoring
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByExampleSelective(@Param("record") BwHealthmonitoring record, @Param("example") BwHealthmonitoringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_healthMonitoring
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByExample(@Param("record") BwHealthmonitoring record, @Param("example") BwHealthmonitoringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_healthMonitoring
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByPrimaryKeySelective(BwHealthmonitoring record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_healthMonitoring
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByPrimaryKey(BwHealthmonitoring record);
}