package com.mama100.lotteryweb.mapper;

import com.mama100.lotteryweb.po.BwSignin;
import com.mama100.lotteryweb.po.BwSigninExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BwSigninMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    long countByExample(BwSigninExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int deleteByExample(BwSigninExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int insert(BwSignin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int insertSelective(BwSignin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    List<BwSignin> selectByExample(BwSigninExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    BwSignin selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByExampleSelective(@Param("record") BwSignin record, @Param("example") BwSigninExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByExample(@Param("record") BwSignin record, @Param("example") BwSigninExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByPrimaryKeySelective(BwSignin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_signin
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByPrimaryKey(BwSignin record);
}