package com.mama100.lotteryweb.mapper;

import com.mama100.lotteryweb.po.BwUseraction;
import com.mama100.lotteryweb.po.BwUseractionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BwUseractionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    long countByExample(BwUseractionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int deleteByExample(BwUseractionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int deleteByPrimaryKey(Long actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int insert(BwUseraction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int insertSelective(BwUseraction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    List<BwUseraction> selectByExample(BwUseractionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    BwUseraction selectByPrimaryKey(Long actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByExampleSelective(@Param("record") BwUseraction record, @Param("example") BwUseractionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByExample(@Param("record") BwUseraction record, @Param("example") BwUseractionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByPrimaryKeySelective(BwUseraction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bw_userAction
     *
     * @mbg.generated Tue Jan 11 16:35:30 CST 2022
     */
    int updateByPrimaryKey(BwUseraction record);
}